/kitti_publisher_node:
  ros__parameters:
    data_path: "/data/Kitti/tracking/training"
    sequence: "0020"
    max_frame: 837
    camera_folder: "image_02"
    lidar_folder: "velodyne"
    oxts_folder: "oxts"
    label_folder: "label_02"
